### ISSUE TITLE
CanExecute is called only once

### ISSUE THREAD

**Issue by gregzhadko** [brminnick/AsyncAwaitBestPractices#18]
I tried to use the package in the WPF project, but it seems that I missed something.

Let say I have the following command:
`SaveQuickEditItemCommand = new AsyncCommand(SaveQuickEditItemCommandExecutedAsync, SaveQuickEditItemCommandCanExecute);`

It looks like the method 
`public bool SaveQuickEditItemCommandCanExecute(object o)`
is called only once, when my control is launched.

However, if I use a simple ICommand interface instead of IAsyncCommand it works differently: it is called each time I change the value in my control (or probably even each time the control was redrawn, I'm not sure).

How can I force IAsyncCommand to work the same way?

**Comment by brminnick** [comment]
Hi Greg!

Can you add a reproduction sample? It sounds like WPF's implementation of `ICommand` may be slightly different than the way `AsyncCommand` implements `ICommand`.

Here's an example demonstrating `AsyncCommand.CanExecuteChanged` from the [Unit Tests](https://github.com/brminnick/AsyncAwaitBestPractices/blob/Release-v3.0.0/Src/AsyncAwaitBestPractices.UnitTests/Tests_AsyncCommand.cs#L113).

```csharp
[Test]
public void AsyncCommand_CanExecuteChanged_Test()
{
    //Arrange
    bool canCommandExecute = false;
    bool didCanExecuteChangeFire = false;

    AsyncCommand command = new AsyncCommand(() => Task.Delay(1000), commandCanExecute);
    command.CanExecuteChanged += handleCanExecuteChanged;

    void handleCanExecuteChanged(object sender, EventArgs e) => didCanExecuteChangeFire = true;
    bool commandCanExecute(object parameter) => canCommandExecute;

    Assert.False(command.CanExecute(null));

    //Act
    canCommandExecute = true;

    //Assert
    Assert.True(command.CanExecute(null));
    Assert.False(didCanExecuteChangeFire);

    //Act
    command.RaiseCanExecuteChanged();

    //Assert
    Assert.True(command.CanExecute(null));
    Assert.True(didCanExecuteChangeFire);
}
```

**Comment by gregzhadko** [comment]
Hello Brandon,
Thank you for your answer.
I think I was able to understand what kind of problem I had.
I'm using MVVM Light toolkit in my project which has advance CommandManager. This class raises CanExecuteChanged event in many general cases, e.g., when I show or hide the IsBusy indicator. This approach allows me to control my command CanExecute state. 
I tried to apply this approach using your library, but it didn't work, that is why I raise this ticket. 
I'm not sure that you will want to create your implementation of CommandManager (I'm not sure that this is the goal of our library), so I will probably try to raise this event manually.
You can close the ticket if you want.

Thank you.
