### ISSUE TITLE
Async / Await != Multithread 

### ISSUE THREAD

**Issue by LunicLynx** [brminnick/AsyncAwaitBestPractices#199]
Just saw your talk. 
the first explanation of Async and await behavior is a bit wrong / misleading.

see:
https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/task-asynchronous-programming-model#BKMK_Threads

Simplified:
Async and await cut long work into pieces and each piece is run on the synchronization context (kind of the windows message loop).
This can be multi threaded, but doesn’t have to.

The idea is, at some point down the chain some long running operation is handled by the OS, for example IO or Network. When the OS is finished the result will be available via a message on the message loop(dependening on the synchronization context). At this point the continuation can be run.

If this seems super strange, build a barebones C++ win32 app, in that case you have to actually build the message loop.
If you debug that app you will notice a lot of the time your app is actually doing, …. Nothing?! The app is Idle.

idle is the next concept to understand. Every process has an allotted time. The time from callback into the synchronization context until returning to the OS measured against the allotted time is the percentage your app is taking from the cpu. Depending on the amount of cores, this will be split accordingly. So 4 cores, without multithreading max 25% cpu usage if your app consumes 100% of the allotted time.

Important to understand is that, redrawing the UI should not take 100% of this time, so the remaining time is spend to finish Async methods. Those as well should be short, otherwise what you described with a hanging UI will happen regardless of using or not using Async / await.

I can recommend the long blog post of stehphen toub.

https://devblogs.microsoft.com/dotnet/how-async-await-really-works/

Best

**Comment by brminnick** [comment]
Thank you. Noted.

**Comment by LunicLynx** [comment]
Very interesting talk! I learned about the frozen types, definitely will use them.

One last suggestion, is the talk really about best practices? Or more about maximum performance?

The given advice for ‚.ConfigureAwait(false)‘, ,return Async‘ and using ValueTask come with caveats, some of them you already mentioned, but in these cases your argument is performance and not optimizing for the least amount of issues.

Anyway, awesome talk, loved the reflection details and am an avid user of hackernews so that as well was hitting home.
Thanks, and have a nice holiday season!
