### ISSUE TITLE
Why is there an in-keyword on a bool parameter

### ISSUE THREAD

**Issue by TiltonJH** [brminnick/AsyncAwaitBestPractices#201]
Hi,

trying to learn from your code (as well as from your presentation: liked them a lot :) ) I found things I can't wrap my head around. So maybe you can enlighten me.

Considering [The ‘in’-modifier and the readonly structs in C#](https://devblogs.microsoft.com/premier-developer/the-in-modifier-and-the-readonly-structs-in-c/) and of that specifically the 2nd point of the conclusion:

> Conclusion
> - The readonly structs are very useful from the design and the performance points of view.
> - If the size of a readonly struct is bigger than `IntPtr.Size` you should pass it as an `in`-parameter for performance reasons.
> - You may consider using the `in`-parameters for reference types to express your intent more clearly.
> - You should never use a non-readonly struct as the in parameters because it may negatively affect performance and could lead to an obscure behavior if the struct is mutable.

I got two questions:

1. Why does the `in bool continueOnCapturedContext` or the `in ConfigureAwaitOptions configureAwaitOptions` parameter use the `in`-Keyword? Or better, why do you have overloads with them? Both are passed around as 32bit values, however the `IntPtr.Size` is at least as large or most likely even 64bit. Furthermore, calling the async method of `HandleSafeFireAndForget` will copy the value and not the reference anyway.
2.  What is the point of using an `in`-keyword on the `in Action<TException>? onException`? Yes, the compiler would not let anyone assign a reference to a different action with in the called method. Me calling the method and passing the action, I don't care what is done to the reference once I passed it. And again, all is lost once the `HandleSafeFireAndForget`-method is called.

**Comment by brminnick** [comment]
I use the `in` keyword for safety, to ensure that I don't override the user inputs to the method parameters.
