### ISSUE TITLE
CanExecuteChanged doesn't fire

### ISSUE THREAD

**Issue by tyrgin** [brminnick/AsyncAwaitBestPractices#23]
Hello!
Thank you very much for your solution! 
I tried "simple" version from https://johnthiriet.com/mvvm-going-async-with-async-command/#
But I faced a problem that I solved without understanding...
The issue is CanExecuteChanged didn't fire on ObservableCollection change. I tried
`collection.CollectionChanged += (sender, e) => CalculateAsync.RaiseCanExecuteChanged();`
But nothing happened.
So the only way I found is to remove the following method
` public void RaiseCanExecuteChanged()
        {
           CanExecuteChanged?.Invoke(this, EventArgs.Empty);
        }`
from your code and replace
`public event EventHandler CanExecuteChanged;`
with 
`public event EventHandler CanExecuteChanged
        {
            add { CommandManager.RequerySuggested += value; }
            remove { CommandManager.RequerySuggested -= value; }
        }`
I'm new with all these things, so I don't really understand what I have changed. It works now but seems with kind of delay in releasing the button after a command
If you have a minute, can you please explain the correct way of fixing my problem, please.
Thanks in advance

**Comment by brminnick** [comment]
Hi @tyrgin!

Can you provide a reproduction sample where `CanExecuteChanged` does not fire? 

It does not automatically fire when the value of `canExecute` changes; you must call `RaiseCanExecuteChanged` after changing the value `canExecute` to fire `CanExecuteChanged`.

Here is a sample from my Unit Tests demonstrating it:
https://github.com/brminnick/AsyncAwaitBestPractices/blob/4695bac4ee0ab1a513a3dd279c8d8dc05d79c927/Src/AsyncAwaitBestPractices.UnitTests/Tests_AsyncCommand.cs#L116-L144

**Comment by tyrgin** [comment]
Hi @brminnick 
Thank you for your answer!
Basically what I have is:
```c#
public class ViewModelCalculate : INotifyPropertyChanged
    {
        private bool isBusy;
        private ObservableCollection<BusSection> busSections;
        public ViewModelCalculate(ObservableCollection<BusSection> busSections)
        {
            this.busSections = busSections;          
        }
        #region Command
        private IAsyncCommand calculateAsync;
        public IAsyncCommand CalculateAsyncCommand => calculateAsync ??
             new AsyncCommand(ExecuteCalculateAsync, CanExecuteCalculate);
        private async Task ExecuteCalculateAsync( )   { ... }
           
        private bool CanExecuteCalculate( ) => busSections.Count() > 0 && !IsBusy;
        #endregion

        #region INotifyPropertyChanged
        public bool IsBusy { get => isBusy; set { isBusy = value; OnPropertyChanged("IsBusy"); } }
        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged([CallerMemberName] string prop = "")
        {   PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(prop));    }
        #endregion
    }
```
And in other ViewModel I update the `busSections` collection. 
As I said I tried to subscribe `CalculateAsync.RaiseCanExecuteChanged()` on  `busSections.CollectionChanged` in `ViewModelCalculate ctor`, but that also gave nothing - `RaiseCanExecuteChanged()` executed but it the event `CanExecuteChanged` was always null in this part
```c#
public void RaiseCanExecuteChanged()
        {
            CanExecuteChanged?.Invoke(this, EventArgs.Empty);
        }
```
Where I should call `RaiseCanExecuteChanged()`?
Actually I've found other hacky way:
```c#
///the VM where i update BusSections collection
public class OtherViewModel
{
   private ObservableCollection<BusSection> busSections
   public ObservableCollection<BusSection> BusSections { get=>busSections; set { busSections = 
                                                                                              value; OnPropertyChanged(); }}
  public ViewModelCalculate VmCalculate {get;set;}
   void UpdateBusSection ()
   {
          ///add item to BusSections
          ///with next line works good
          OnPropertyChanged("VmCalculate");
   }
}
```
Sorry for messy explanation, i've tried a few options, eventually came to `OnPropertyChanged("VmCalculate")` without calling `RaiseCanExecuteChanged()`, but i believe there is should be right way.

**Comment by tyrgin** [comment]
@brminnick it has occurred to me today that I RaiseCanExecuteChanged always for a new instance of Command...
so I changed
```c#
private IAsyncCommand calculateAsync;
        public IAsyncCommand CalculateAsyncCommand => calculateAsync ??
             new AsyncCommand(ExecuteCalculateAsync, CanExecuteCalculate);
```
to this
```c#
public IAsyncCommand<string> CalculateAsyncCommand {
            get
            {
                calculateAsync ??= new AsyncCommand<string>(x => ExecuteCalculateAsync(x), x => CanExecuteCalculate(x),
                    new ErrorHandler(dialogService, "calculation exception", "message"));
                return calculateAsync;                
            }
        }
```
And now it works without hacky OnPropertyChanged :)
Is this solve ok? Or I should change anything?

**Comment by tyrgin** [comment]
How do you think, is it ok to invoke `RaiseCanExecuteChanged` from different `ViewModel`?

**Comment by brminnick** [comment]
@tyrgin 

For your example, you'll need to call `CalculateAsyncCommand.RaiseCanExecuteChanged()` any time the value of `bool CanExecuteCalculate()` changes.

Because `bool CanExecuteCalculate()` references both `busSections.Count()` and `IsBusy`, you need to call `CalculateAsyncCommand.RaiseCanExecuteChanged()` every time the value of `busSections.Count()` and `IsBusy` changes.

Here's the updated code:

```csharp
public class ViewModelCalculate : INotifyPropertyChanged
{
        private bool isBusy;
        private IAsyncCommand calculateAsync;
        private ObservableCollection<BusSection> busSections;

        public ViewModelCalculate(ObservableCollection<BusSection> busSections)
        {
            this.busSections = busSections;          
        }

        public event PropertyChangedEventHandler PropertyChanged;

        public IAsyncCommand CalculateAsyncCommand => calculateAsync ??
             (calculateAsync = new AsyncCommand(ExecuteCalculateAsync, CanExecuteCalculate));
        
        public bool IsBusy 
        { 
            get => isBusy; 
            set
            {
                isBusy = value; 
                OnPropertyChanged();
                CalculateAsyncCommand.RaiseCanExecuteChanged();
            }
        }

        private async Task ExecuteCalculateAsync( )  
        {
            // Whenever you reference `busSections`, call `CalculateAsyncCommand.RaiseCanExecuteChanged()`
            // Here's an example:
            //     busSections.Clear();
            //     CalculateAsyncCommand.RaiseCanExecuteChanged();
            // Here's another example:
            //     busSections.Add(new BusStation());
            //     CalculateAsyncCommand.RaiseCanExecuteChanged();
        }
           
        private bool CanExecuteCalculate( ) => busSections.Count() > 0 && !IsBusy;

        public void OnPropertyChanged([CallerMemberName] string prop = "") =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(prop));
}

**Comment by brminnick** [comment]
And thanks so much for the feedback!

I've updated the docs to include an example of `CanExecuteChanged`:

https://github.com/brminnick/AsyncAwaitBestPractices/blob/master/README.md#asyncawaitbestpracticesmvvm-2

**Comment by tyrgin** [comment]
@brminnick thank you very much for your help with code and explanation! :)
I really appreciate it!)
