### ISSUE TITLE
CanExecute issue

### ISSUE THREAD

**Issue by AndrzejKl** [brminnick/AsyncAwaitBestPractices#24]
Hi.
All details described here: 
[https://stackoverflow.com/q/59137992/2120193](https://stackoverflow.com/q/59137992/2120193)

**Comment by brminnick** [comment]
Hi @AndrzejKl!

You'll need to call `AsyncCommand.RaiseCanExecuteChanged()` any time the value of `CanExecute` changes.

I've updated the docs with an example here: https://github.com/brminnick/AsyncAwaitBestPractices#asyncawaitbestpracticesmvvm-2

There is also an example in this previous Issue: https://github.com/brminnick/AsyncAwaitBestPractices/issues/23#issuecomment-548097367

And here is an example of how I'm using it in one of my apps: https://github.com/brminnick/SimpleXamarinGraphQL/blob/master/SimpleXamarinGraphQL/ViewModels/GraphQLViewModel.cs#L23

**Comment by AndrzejKl** [comment]
I think I've found Issue  - question I'm doing something wrong or it's really issue (or maybe it's an Fody issue). 
Everything works if command and canExecute bool are declared in the same class (then even I don't must to call `command.RaiseCanExecuteChanged()` event), but if bool is declared in `ViewModelBase`, then nothing will help - it's just not working. In this example I'm working with `Fody.PropertyChanged`:
This will not work (SaveCommand Button always disabled):

View: 
```` xaml
 <Window.DataContext>
        <local:MainWindowViewModel />
    </Window.DataContext>
    <StackPanel>

        <Button Command="{Binding ClickCommand}"
                Content="Click"
                Margin="20" />

        <TextBlock Text="{Binding Value}"
                   HorizontalAlignment="Center"
                   Margin="20" />

        <Button Command="{Binding SaveCommand}"
                Content="Save"
                Margin="20" />
    </StackPanel>
````
MainWindowViewModel:
```` c#
public class MainWindowViewModel : ViewModelBase, INotifyPropertyChanged
    {
        public IAsyncCommand ClickCommand => new AsyncCommand(() => ClickCommand_Executed(), _ => true);

        public IAsyncCommand SaveCommand => new AsyncCommand(() => SaveCommand_Executed(), _ => IsValid);

        private async Task SaveCommand_Executed()
        {
        }

        private async Task ClickCommand_Executed()
        {
            await Task.Delay(500);
            Value++;
            SaveCommand.RaiseCanExecuteChanged();
        }
    }
````
ViewModelBase:
```` c#
public class ViewModelBase : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        public bool IsValid => Value % 2 == 0;

        public int Value { get; set; } = 1;
    }
````
But if I just move `IsValid` and `Value` properties to `MainWindowViewModel`, then I can even delete `RaiseCanExecuteChanged` lines and it will work;
