### ISSUE TITLE
Error when running from signed assembly

### ISSUE THREAD

**Issue by mooola** [brminnick/AsyncAwaitBestPractices#25]
I get the following exception when running from a signed assembly.  Can we get your code signed?

TIA.

System.IO.FileLoadException: 'Could not load file or assembly 'AsyncAwaitBestPractices.MVVM, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

**Comment by brminnick** [comment]
Is this a compiler warning or a compiler error?

**Comment by brminnick** [comment]
This tool may also provide a helpful workaround for now: https://github.com/dsplaisted/strongnamer

**Comment by mooola** [comment]
Compiler error.

**Comment by brminnick** [comment]
Hi Gene! 

I've added Assembly Signing in v4.1.0-pre2.

Let me know if v4.1.0-pre2 works for you! Once confirmed, I'll close the issue 👍 

https://www.nuget.org/packages/AsyncAwaitBestPractices.MVVM/4.1.0-pre2

**Comment by brminnick** [comment]
Now available in v4.1.0:
https://www.nuget.org/packages/AsyncAwaitBestPractices.MVVM/4.1.0
