### ISSUE TITLE
Is "Sealed" necessary for AsyncCommand?

### ISSUE THREAD

**Issue by andrekiba** [brminnick/AsyncAwaitBestPractices#27]
Hi Brandon and thanks in advance.
Do you remember `DependentCommand`?
The idea is to re-evaluate the `CanExecute` when one dependent property changes.
It would be nice to have the same thing here...something like `DependentAsyncCommand`.
But `AsyncCommand` is a sealed class, it can't be used as a base class and so it means I have to copy-paste to re-implement what is already inside.
Is there a reason?

**Comment by brminnick** [comment]
Hi @andrekiba!

Yea, we can totally unseal `AsyncCommand`.

I'd love for you to get credit for this update! Do you mind sending me a quick pull request with `sealed` removed from the following classes:
- [ ] Remove `sealed` from `AsyncCommand`
- [ ] Remove `sealed` from `AsyncCommand<T>`
- [ ] Remove `sealed` from `AsyncValueCommand`
- [ ] Remove `sealed` from `AsyncValueCommand<T>`

**Comment by brminnick** [comment]
https://github.com/brminnick/AsyncAwaitBestPractices/pull/28

https://www.nuget.org/packages/AsyncAwaitBestPractices.MVVM/4.1.0-pre1
