### ISSUE TITLE
ArgumentException with Dynamic Handlers

### ISSUE THREAD

**Issue by alexhelms** [brminnick/AsyncAwaitBestPractices#36]
This issue is for .NET Core 3.1 but I believe it would also occur in .NET Framework 4.8 (and probably lower versions).

This issue is for AsyncAwaitBestPractices V4.2.0.

I believe `EventManagerService.HandleEvent` is throwing exceptions trying to call `Invoke` on a dynamic delegate that requires `DynamicInvoke` to be called.

I discovered this in unit tests in my project. I am using FluentAssertions and checking for property changed events to be fired. See the example below:

```
var vm = new ViewModel();
using var subject = vm.Monitor();
vm.SomeMethod();
subject.Should().RaisePropertyChangeFor(x => x.Value);
```

I you are not familiar with FluentAssertions, calling `vm.Monitor()` dynamically creates handlers for all events on the `vm` object so you can assert behavior of the events. 

Here is the stack trace from when the exception occurs.

```
  Message: 
    System.ArgumentException : MethodInfo must be a runtime MethodInfo object. (Parameter 'this')
  Stack Trace: 
    RTDynamicMethod.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    EventManagerService.HandleEvent(String& eventName, Object& sender, Object& eventArgs, Dictionary`2& eventHandlers)
    WeakEventManager.RaiseEvent(Object& sender, Object& eventArgs, String& eventName)
    WeakEventManager.RaiseEvent(Object sender, Object eventArgs, String eventName)
    VMBase.OnPropertyChanged(String& propertyName) line 322
```

In `EventManagerService` here https://github.com/brminnick/AsyncAwaitBestPractices/blob/master/Src/AsyncAwaitBestPractices/WeakEventManager/EventManagerService.cs#L54 you can see it simply calls `Invoke`. The correct behavior should be to see if it is a dynamic object and call DynamicInvoke when appropriate.

Looking at the coreclr source here: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/System.Private.CoreLib/src/System/Reflection/Emit/DynamicMethod.cs#L628 you can see that because it is a dynamic delegate, invoke is not allowed and so this is the source of the exception.

**Comment by brminnick** [comment]
Thanks Alex! Dynamic Methods are something I didn't even know existed in C#!

Just out of curiosity - can you point me to a sample app that uses dynamic methods? I'd love to understand them better myself 😃

**Comment by alexhelms** [comment]
Thanks!

I have little experience with actually writing code that uses dynamic methods but I use libraries that require them for how they work -- FluentAssertions and Moq (or any mocking library) are notable examples.

Here are some examples on the dotnet docs about how to actually use them:
https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-define-and-execute-dynamic-methods
