### ISSUE TITLE
Possible improvement for explicit ICommand.Execute() implementation in AsyncCommand?

### ISSUE THREAD

**Issue by Eagle3386** [brminnick/AsyncAwaitBestPractices#42]
While looking at your awesome example implementation of `IAsyncCommand`, I noticed that the explicit implementation of `ICommand.Execute()` over at https://github.com/brminnick/AsyncAwaitBestPractices/blob/1678be914aa2976d82bc386e3b18dc0df1e7e494/Src/AsyncAwaitBestPractices.MVVM/AsyncValueCommand.cs#L143
points to `_execute()` instead of `ExecuteAsync()` (2 lines above) - out of curiosity: why's that?

Because if the latter would be used, an implementer would have a single point of customization, e. g. for extension of `ExecuteAsync()` by setting an `IsExecuting` property via `try ... finally` (checked inside `CanExecute()`, of course) to provide for efficient prevention of consecutive calls prior to actually finishing the first execution.

**Comment by brminnick** [comment]
`ICommand.Execute` returns `void` which is why I’m leveraging `SafeFireAndForget` instead of `ExecuteAsync` which returns a `Task`.

Feel free to open a PR if you have ideas on how to improve it!
